version: '3'

services:
  back:
    container_name: freelinette-back
    restart: always
    build: ./nestJS
    ports:
     - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./nestJS:/app/nestJS
      - ./cypress:/app/nestJS/cypress
    
  db:
    container_name: freelinette-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=${DATABASE_NAME}
      # - MONGODB_INITDB_ROOT_USERNAME=${DATABASE_USER}
      # - MONGODB_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    # volumes:
      # - ./mongoDB/scripts/:/docker-entrypoint-initdb.d/
      # - ./mongoDB/data:/data/db

      # - MONGODB_USERNAME=${DATABASE_USER}
      # - MONGODB_PASSWORD=${DATABASE_PASSWORD}

  # cgi-cypress:
  #   container_name: cgi-cypress
  #   build: ./CGI-Cypress
  #   restart: always
  #   working_dir: /
  #   volumes:
  #     - ./cypress:/app/cypress
