FROM ubuntu:latest

RUN apt update &&\
	apt install wget npm -y

# RUN npm install -g n npm@latest &&\
# 	n latest

# RUN /app/cypress-runtime/node_modules/.bin/cypress install


COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
# RUN chown root.root -R /root

ENTRYPOINT sh /docker-entrypoint.sh