FROM ubuntu:latest

RUN apt update &&\
	apt install wget npm fonts-liberation libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

RUN npm install -g n npm@latest &&\
	n latest

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT sh /docker-entrypoint.sh