###################
# BUILD FOR PROD #
###################


FROM ubuntu:latest as prod

RUN apt update &&\
	apt install wget npm firefox libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

# install chrome of cypress
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'; \
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - ; \
	apt update; \
	apt install google-chrome-stable -y

# install firefox for cypress
RUN wget -O /tmp/firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US" && \
	tar -xjf /tmp/firefox.tar.bz2 -C /opt && \
	rm /tmp/firefox.tar.bz2 && \
	ln -fs /opt/firefox/firefox /usr/bin/firefox

RUN npm install -g n npm@latest &&\
	n latest

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

COPY . /app/nestJS
RUN mkdir -p /app/nestJS/cypress/e2e
RUN mkdir -p /app/nestJS/cypress/screen

ENTRYPOINT sh /docker-entrypoint.sh


###################
# BUILD FOR DEV  #
###################

FROM ubuntu:latest as dev

RUN apt update &&\
	apt install wget npm firefox libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

# install chrome of cypress
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'; \
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - ; \
	apt update; \
	apt install google-chrome-stable -y

# install firefox for cypress
RUN wget -O /tmp/firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US" && \
	tar -xjf /tmp/firefox.tar.bz2 -C /opt && \
	rm /tmp/firefox.tar.bz2 && \
	ln -fs /opt/firefox/firefox /usr/bin/firefox

RUN npm install -g n npm@latest &&\
	n latest

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT sh /docker-entrypoint.sh