FROM ubuntu:latest

RUN apt update &&\
	apt install wget curl apache2 fonts-liberation npm libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

# RUN npm install -g n npm@latest &&\
# 	n latest
# #

# setup of the apache server and the cgi script
RUN source /etc/apache2/envvars; \
	cd /etc/apache2/mods-enabled; \
	ln -s ../mods-available/cgi.load; \
	service apache2 restart; \
	chown -R www-data:www-data /var/www
COPY cypress-run.sh /usr/lib/cgi-bin/
RUN chmod +x /usr/lib/cgi-bin/cypress-run.sh

RUN mkdir /app
RUN cd /app; \
	export CYPRESS_CACHE_FOLDER=/app/.cache;\
	npm install cypress;
COPY cypress.config.js /app/

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT bash /docker-entrypoint.sh